-- Schema inicial do Nexus Food (Fase 2): plataforma, cardápio, clientes e pedidos.
-- SQL mantido portável entre PostgreSQL (produção) e H2 em modo PostgreSQL (testes).

CREATE TABLE restaurantes (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                      VARCHAR(255)   NOT NULL,
    slug                      VARCHAR(255)   NOT NULL,
    telefone                  VARCHAR(255),
    endereco                  VARCHAR(255),
    logo_url                  VARCHAR(255),
    fuso_horario              VARCHAR(64)    NOT NULL,
    hora_virada_dia           TIME           NOT NULL,
    aceitando_pedidos         BOOLEAN        NOT NULL,
    aceita_retirada           BOOLEAN        NOT NULL,
    aceita_entrega            BOOLEAN        NOT NULL,
    aceita_consumo_local      BOOLEAN        NOT NULL,
    tipo_taxa_entrega         VARCHAR(32)    NOT NULL,
    taxa_entrega_fixa         NUMERIC(12, 2) NOT NULL,
    pedido_minimo             NUMERIC(12, 2) NOT NULL,
    tempo_preparo_estimado_min INTEGER       NOT NULL,
    plano_saas                VARCHAR(32)    NOT NULL,
    status_assinatura_saas    VARCHAR(32)    NOT NULL,
    data_fim_trial            DATE,
    stripe_customer_id        VARCHAR(255),
    stripe_subscription_id    VARCHAR(255),
    criado_em                 TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_restaurantes_slug UNIQUE (slug)
);

CREATE TABLE usuarios (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id         BIGINT       NOT NULL REFERENCES restaurantes (id),
    nome                   VARCHAR(255) NOT NULL,
    email                  VARCHAR(255) NOT NULL,
    cpf                    VARCHAR(11),
    senha_hash             VARCHAR(255) NOT NULL,
    papel                  VARCHAR(32)  NOT NULL,
    ativo                  BOOLEAN      NOT NULL,
    reset_senha_token      VARCHAR(255),
    reset_senha_expira_em  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT uk_usuarios_cpf UNIQUE (cpf)
);
CREATE INDEX idx_usuarios_restaurante ON usuarios (restaurante_id);

CREATE TABLE bairros_entrega (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id  BIGINT         NOT NULL REFERENCES restaurantes (id),
    nome            VARCHAR(120)   NOT NULL,
    taxa            NUMERIC(12, 2) NOT NULL,
    ativo           BOOLEAN        NOT NULL
);
CREATE INDEX idx_bairros_restaurante ON bairros_entrega (restaurante_id);

CREATE TABLE categorias (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id  BIGINT       NOT NULL REFERENCES restaurantes (id),
    nome            VARCHAR(120) NOT NULL,
    ordem           INTEGER      NOT NULL,
    ativa           BOOLEAN      NOT NULL
);
CREATE INDEX idx_categorias_restaurante ON categorias (restaurante_id);

CREATE TABLE produtos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id  BIGINT         NOT NULL REFERENCES restaurantes (id),
    categoria_id    BIGINT         NOT NULL REFERENCES categorias (id),
    nome            VARCHAR(160)   NOT NULL,
    descricao       VARCHAR(1000),
    preco           NUMERIC(12, 2) NOT NULL,
    imagem_url      VARCHAR(500),
    disponivel      BOOLEAN        NOT NULL,
    ativo           BOOLEAN        NOT NULL,
    ordem           INTEGER        NOT NULL,
    criado_em       TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_produtos_restaurante ON produtos (restaurante_id);
CREATE INDEX idx_produtos_categoria ON produtos (categoria_id);

CREATE TABLE clientes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id  BIGINT       NOT NULL REFERENCES restaurantes (id),
    telefone        VARCHAR(20)  NOT NULL,
    nome            VARCHAR(160) NOT NULL,
    criado_em       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_clientes_restaurante_telefone UNIQUE (restaurante_id, telefone)
);

CREATE TABLE pedidos (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id         BIGINT         NOT NULL REFERENCES restaurantes (id),
    cliente_id             BIGINT         NOT NULL REFERENCES clientes (id),
    numero_dia             INTEGER        NOT NULL,
    codigo_publico         VARCHAR(36)    NOT NULL,
    chave_idempotencia     VARCHAR(64)    NOT NULL,
    modalidade             VARCHAR(32)    NOT NULL,
    status                 VARCHAR(32)    NOT NULL,
    forma_pagamento        VARCHAR(32)    NOT NULL,
    troco_para             NUMERIC(12, 2),
    endereco_entrega       VARCHAR(500),
    bairro_entrega         VARCHAR(120),
    observacao             VARCHAR(500),
    subtotal               NUMERIC(12, 2) NOT NULL,
    taxa_entrega           NUMERIC(12, 2) NOT NULL,
    total                  NUMERIC(12, 2) NOT NULL,
    dia_operacional        DATE           NOT NULL,
    pronto_previsto_para   TIMESTAMP WITH TIME ZONE NOT NULL,
    criado_em              TIMESTAMP WITH TIME ZONE NOT NULL,
    confirmado_em          TIMESTAMP WITH TIME ZONE,
    em_preparo_em          TIMESTAMP WITH TIME ZONE,
    pronto_em              TIMESTAMP WITH TIME ZONE,
    saiu_para_entrega_em   TIMESTAMP WITH TIME ZONE,
    concluido_em           TIMESTAMP WITH TIME ZONE,
    cancelado_em           TIMESTAMP WITH TIME ZONE,
    motivo_cancelamento    VARCHAR(40),
    cancelado_por          VARCHAR(20),
    CONSTRAINT uk_pedidos_codigo_publico UNIQUE (codigo_publico),
    CONSTRAINT uk_pedidos_idempotencia UNIQUE (restaurante_id, chave_idempotencia),
    CONSTRAINT uk_pedidos_numero_dia UNIQUE (restaurante_id, dia_operacional, numero_dia)
);
CREATE INDEX idx_pedidos_restaurante_status ON pedidos (restaurante_id, status);
CREATE INDEX idx_pedidos_restaurante_cliente ON pedidos (restaurante_id, cliente_id, concluido_em);

CREATE TABLE itens_pedido (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id       BIGINT         NOT NULL REFERENCES pedidos (id),
    produto_id      BIGINT         NOT NULL REFERENCES produtos (id),
    nome_produto    VARCHAR(160)   NOT NULL,
    preco_unitario  NUMERIC(12, 2) NOT NULL,
    quantidade      INTEGER        NOT NULL,
    subtotal        NUMERIC(12, 2) NOT NULL,
    observacao      VARCHAR(300)
);
CREATE INDEX idx_itens_pedido_pedido ON itens_pedido (pedido_id);
CREATE INDEX idx_itens_pedido_produto ON itens_pedido (produto_id);

CREATE TABLE pedido_eventos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id        BIGINT      NOT NULL REFERENCES pedidos (id),
    status_anterior  VARCHAR(32),
    status_novo      VARCHAR(32) NOT NULL,
    ocorrido_em      TIMESTAMP WITH TIME ZONE NOT NULL,
    usuario_id       BIGINT REFERENCES usuarios (id)
);
CREATE INDEX idx_pedido_eventos_pedido ON pedido_eventos (pedido_id);
