-- Fase 4: Nexus Analytics — resumos diários, notas do Nexus Score e insights.

-- Resumo de cada dia operacional fechado. Somas (não médias) para poder juntar dias em janelas.
CREATE TABLE snapshots_diarios (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id          BIGINT         NOT NULL REFERENCES restaurantes (id),
    dia                     DATE           NOT NULL,
    pedidos_recebidos       INTEGER        NOT NULL,
    pedidos_concluidos      INTEGER        NOT NULL,
    cancelados_restaurante  INTEGER        NOT NULL,
    cancelados_cliente      INTEGER        NOT NULL,
    faturamento             NUMERIC(14, 2) NOT NULL,
    itens_vendidos          INTEGER        NOT NULL,
    clientes_unicos         INTEGER        NOT NULL,
    clientes_novos          INTEGER        NOT NULL,
    pedidos_com_pronto      INTEGER        NOT NULL,
    prontos_no_prazo        INTEGER        NOT NULL,
    pedidos_por_hora        VARCHAR(200)   NOT NULL,
    versao_calculo          INTEGER        NOT NULL,
    calculado_em            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_snapshots_diarios UNIQUE (restaurante_id, dia)
);

CREATE TABLE snapshots_produtos_diarios (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id  BIGINT         NOT NULL REFERENCES restaurantes (id),
    dia             DATE           NOT NULL,
    produto_id      BIGINT         NOT NULL REFERENCES produtos (id),
    quantidade      INTEGER        NOT NULL,
    faturamento     NUMERIC(14, 2) NOT NULL,
    CONSTRAINT uk_snapshots_produtos UNIQUE (restaurante_id, dia, produto_id)
);

-- Uma nota por restaurante, dia de referência e versão da regra.
CREATE TABLE nexus_scores (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id           BIGINT        NOT NULL REFERENCES restaurantes (id),
    dia                      DATE          NOT NULL,
    regra_versao             VARCHAR(10)   NOT NULL,
    situacao                 VARCHAR(20)   NOT NULL,
    nota                     INTEGER,
    faixa                    VARCHAR(20),
    peso_valido              NUMERIC(6, 4) NOT NULL,
    dias_historico           INTEGER       NOT NULL,
    pedidos_concluidos_janela INTEGER      NOT NULL,
    motivo_sem_nota          VARCHAR(300),
    calculado_em             TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_nexus_scores UNIQUE (restaurante_id, dia, regra_versao)
);

CREATE TABLE nexus_score_areas (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    score_id     BIGINT        NOT NULL REFERENCES nexus_scores (id) ON DELETE CASCADE,
    area         VARCHAR(20)   NOT NULL,
    nota         NUMERIC(5, 1),
    peso         NUMERIC(6, 4) NOT NULL,
    peso_valido  NUMERIC(6, 4) NOT NULL,
    exibida      BOOLEAN       NOT NULL
);
CREATE INDEX idx_nexus_score_areas_score ON nexus_score_areas (score_id);

CREATE TABLE nexus_score_indicadores (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    score_id      BIGINT         NOT NULL REFERENCES nexus_scores (id) ON DELETE CASCADE,
    area          VARCHAR(20)    NOT NULL,
    codigo        VARCHAR(40)    NOT NULL,
    valor         NUMERIC(14, 4),
    pontos        NUMERIC(5, 1),
    peso_efetivo  NUMERIC(6, 4)  NOT NULL,
    status        VARCHAR(20)    NOT NULL,
    motivo        VARCHAR(300),
    amostra       BIGINT         NOT NULL
);
CREATE INDEX idx_nexus_score_indicadores_score ON nexus_score_indicadores (score_id);

CREATE TABLE nexus_insights (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id    BIGINT         NOT NULL REFERENCES restaurantes (id),
    dia               DATE           NOT NULL,
    template          VARCHAR(40)    NOT NULL,
    template_versao   INTEGER        NOT NULL,
    severidade        VARCHAR(20)    NOT NULL,
    prioridade        INTEGER        NOT NULL,
    valor_referencia  NUMERIC(14, 4),
    parametros        VARCHAR(2000)  NOT NULL,
    texto             VARCHAR(500)   NOT NULL,
    criado_em         TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_nexus_insights_restaurante_dia ON nexus_insights (restaurante_id, dia);
