-- Adicionais e variações: cada produto tem grupos de opções (Tamanho, Borda, Adicionais, Sabores).
-- minimo/maximo: quantas opções do grupo o cliente escolhe (minimo >= 1 = obrigatório).
-- cobranca: SOMA (soma o preço das escolhidas), MAIOR (cobra só a mais cara, ex.: meio a meio)
-- ou MEDIA (média das escolhidas).
CREATE TABLE grupos_opcoes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id  BIGINT      NOT NULL REFERENCES produtos (id),
    nome        VARCHAR(80) NOT NULL,
    minimo      INTEGER     NOT NULL,
    maximo      INTEGER     NOT NULL,
    cobranca    VARCHAR(16) NOT NULL,
    ordem       INTEGER     NOT NULL
);
CREATE INDEX idx_grupos_opcoes_produto ON grupos_opcoes (produto_id);

CREATE TABLE opcoes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grupo_id    BIGINT         NOT NULL REFERENCES grupos_opcoes (id),
    nome        VARCHAR(80)    NOT NULL,
    preco       NUMERIC(12, 2) NOT NULL,
    disponivel  BOOLEAN        NOT NULL,
    ordem       INTEGER        NOT NULL
);
CREATE INDEX idx_opcoes_grupo ON opcoes (grupo_id);

-- Cópia do que foi escolhido, como já acontece com nome e preço do produto: mudar ou remover a
-- opção depois não reescreve pedidos antigos (por isso opcao_id não tem chave estrangeira).
CREATE TABLE itens_pedido_opcoes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id     BIGINT         NOT NULL REFERENCES itens_pedido (id),
    opcao_id    BIGINT,
    nome_grupo  VARCHAR(80)    NOT NULL,
    nome_opcao  VARCHAR(80)    NOT NULL,
    preco       NUMERIC(12, 2) NOT NULL
);
CREATE INDEX idx_itens_pedido_opcoes_item ON itens_pedido_opcoes (item_id);
